✨ Feat : 프로젝트 수정기능 추가
BoSeong-With-Kids/TBBCloneProject-BE pull request #11
Opened 2022-12-25 04:08 UTC by seonghyun-1

## PR 체크사항
PR이 다음 사항을 만족하는지 확인해주세요.

- [x] 커밋 제목 규칙
- [x] 커밋 메시지 작성 가이드라인
- [x] 라벨, 담당자, 리뷰어 지정

## PR 타입
어떤 유형의 PR인지 체크해주세요.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## PR 설명
프로젝트 수정기능을 추가했습니다.

## 작업사항
- 프로젝트 수정 요청 시 변경

2022-12-26 02:38 UTC, tjvm0877 requested changes
리뷰 확인 부탁드립니다.

2022-12-26 02:38 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/project/controller/ProjectController.java
> +        return new ResponseEntity<>(responseDto, HttpStatus.OK);
`return new ResponseEntity<>(responseDto, HttpStatus.OK);` 에서 `<>`는 지워도 될 것 같습니다.

2022-12-26 02:38 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/project/dto/ProjectCreateRequestDto.java
> +public class ProjectCreateRequestDto {
사용하지 않는 DTO라면 삭제해도 될 것 같습니다.

2022-12-26 02:38 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/project/entity/Project.java
> +    public void update(ProjectUpdateRequestDto projectUpdateRequestDto) {
ENtity가 Dto를 매개변수를 받게되는 형태가 아닌 mapper를 이용해서 구현부탁드립니다.

2022-12-26 08:08 UTC, seonghyun-1 commented on src/main/java/com/team1/TBBCloneCoding/project/controller/ProjectController.java
> +        return new ResponseEntity<>(responseDto, HttpStatus.OK);
확인하고 수정했습니다!

2022-12-26 08:09 UTC, seonghyun-1 commented on src/main/java/com/team1/TBBCloneCoding/project/dto/ProjectCreateRequestDto.java
> +public class ProjectCreateRequestDto {
확인하고 수정했습니다!

2022-12-27 04:36 UTC, tjvm0877 approved these changes

2022-12-27 15:34 UTC, JeongO41 approved these changes

2022-12-27 15:47 UTC, merged