✨ Feat : 로그인, 회원가입, 시큐리티 기능 구현
BoSeong-With-Kids/TBBCloneProject-BE pull request #26
Opened 2022-12-26 09:14 UTC by teabear12

## PR 체크사항
PR이 다음 사항을 만족하는지 확인해주세요.

- [x] 커밋 제목 규칙
- [x] 커밋 메시지 작성 가이드라인
- [x] 라벨, 담당자, 리뷰어 지정

## PR 타입
어떤 유형의 PR인지 체크해주세요.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## PR 설명
로그인, 회원가입 기능 구현
시큐리티 기능 추가

## 작업사항
1. 로그인, 회원가입
-MemberController 추가
-MemberService 추가
-LoginRequestDto, SignupRequestDto 추가
-MemberRepository 추가

2. security 패키지 추가
->config(WebSecurityConfig) 추가
->jwt(JwtAuthFilter, JwtUtil) 추가
->UserDetailsImpl추가
->UserDetailsServiceImpl추가

2022-12-26 11:14 UTC, tjvm0877 requested changes

2022-12-26 11:14 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/TbbCloneCodingApplication.java
> +	public void started() {
이부분의 역할에 대해 말씀해주실 수 있나요?

2022-12-26 11:14 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/common/Response.java
> +public class Response {
이미존재하는 `ResponseDto`와 다른 형식을 사용하는 이유가 있나요?

2022-12-26 11:14 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/common/dto/ResponseDto.java
> +public class ResponseDto<T> extends Response {
`ResposneDto`를 바로 사용하는 것이 아닌 `Response`를 상속받고 똑같은 형식을 쓰는 이유를 알 수 있을까요?

2022-12-26 11:14 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/member/entity/Member.java
> +    private MemberRoleEnum role;
저희 프로젝트는 아직 권한 관련 이야기가 없었는데 Entity에 회원 권환 속성을 넣은 이유가 있을까요.

2022-12-26 11:14 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/member/entity/MemberRoleEnum.java
> +public enum MemberRoleEnum {
저희 프로젝트는 아직 권한 관련 이야기가 없었는데 Entity에 회원 권환 속성을 넣은 이유가 있을까요.

2022-12-26 11:14 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/member/service/MemberService.java
> +    @Value("{admin.token}")
저희 프로젝트는 아직 권한 관련 이야기가 없었는데 Entity에 회원 권환 속성을 넣은 이유가 있을까요.

2022-12-26 11:14 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/project/entity/ImageTable.java
> +public class ImageTable {
이슈 #21
이걸로 Entity의 이름을 바꿨는데 또 변경하신 이유가 있을까요?

2022-12-26 11:14 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/security/jwt/JwtUtil.java
> +//    private static final long TOKEN_TIME = 60 * 60 * 1000L;
토큰 유효기간 설정을 auth.properties로 빼신것 같은데 이 주석은 지워주셔도 될 것 같습니다.

2022-12-26 11:14 UTC, tjvm0877 commented on src/main/resources/application.properties
> +token_time=60 * 60 * 1000L
auth.properties에 있는 `token_time`이 있는데 여기에도 추가하신 이유를 여쭤봐도 될까요?

2022-12-26 11:17 UTC, tjvm0877 requested changes
PR 담당자, 리뷰어, 라벨 설정해주세요. 이슈도 close해주시고요.

2022-12-26 12:15 UTC, teabear12 commented on src/main/resources/application.properties
> +token_time=60 * 60 * 1000L
원래는 auth.properties에 spring.profiles.includ를 사용하여 코드 실행하면 되는 것으로 알고 작성하였는데, 버전이 바뀌면서 spring.profiles.includ 사용하는 법이 바뀌었다고 하는데, 어떻게 사용하는지 잘 모르겠어서 그냥 두 값을 application.properties으로 보냈습니다.

개선 : auth.properties 지우기, 주석 지우기

2022-12-26 12:15 UTC, teabear12 commented on src/main/java/com/team1/TBBCloneCoding/security/jwt/JwtUtil.java
> +//    private static final long TOKEN_TIME = 60 * 60 * 1000L;
주석 지우겠습니다

2022-12-26 12:16 UTC, teabear12 commented on src/main/java/com/team1/TBBCloneCoding/project/entity/ImageTable.java
> +public class ImageTable {
원래는 ProjectImage로 변경하였는데, 잘못 올라간 것 같습니다. 확인 후 다시 풀리퀘하겠습니다.

2022-12-26 12:17 UTC, teabear12 commented on src/main/java/com/team1/TBBCloneCoding/member/service/MemberService.java
> +    @Value("{admin.token}")
원래는 필요없는 값이라 지웠습니다. 그런데 pr을 잘못하여 올라간 것 같습니다. 다시 올리겠습니다.

2022-12-26 12:17 UTC, teabear12 commented on src/main/java/com/team1/TBBCloneCoding/member/entity/MemberRoleEnum.java
> +public enum MemberRoleEnum {
다른 코드 커스텀 과정에서 인지하지 못하고 넣은 것 같습니다.
확인하고 커스텀 진행하겠습니다.

2022-12-26 12:18 UTC, teabear12 commented on src/main/java/com/team1/TBBCloneCoding/member/entity/Member.java
> +    private MemberRoleEnum role;
다른 코드 커스텀 과정에서 인지하지 못하고 넣은 것 같습니다.
확인하고 커스텀 진행하겠습니다.

2022-12-26 12:19 UTC, teabear12 commented on src/main/java/com/team1/TBBCloneCoding/common/dto/ResponseDto.java
> +public class ResponseDto<T> extends Response {
제네릭에 대한 이해가 부족하여 다른 코드를 그대로 사용하였습니다. 피드백 부분을 참고하여 코드 수정들어가겠습니다.

2022-12-26 12:19 UTC, teabear12 commented on src/main/java/com/team1/TBBCloneCoding/common/Response.java
> +public class Response {
제네릭에 대한 이해가 부족하여 다른 코드를 그대로 사용하였습니다. 피드백 부분을 참고하여 코드 수정들어가겠습니다.

2022-12-26 12:22 UTC, teabear12 commented on src/main/java/com/team1/TBBCloneCoding/TbbCloneCodingApplication.java
> +	public void started() {
정확하게 인지하지 못한 내용입니다. 내용에 대해 찾아본 후 수정이나 삭제하도록 하겠습니다.

2022-12-27 01:53 UTC, tjvm0877 approved these changes

2022-12-27 01:55 UTC, seonghyun-1 approved these changes
확인했습니다!

2022-12-27 02:40 UTC, merged