✨[feat] Project 생성기능 추가수정 ( Valid 및 Exception 추가 )
BoSeong-With-Kids/TBBCloneProject-BE pull request #8
Opened 2022-12-24 17:29 UTC by seonghyun-1

- Valid 추가
- ValidException 추가

## PR 체크사항
PR이 다음 사항을 만족하는지 확인해주세요.

- [x] 커밋 제목 규칙
- [x] 커밋 메시지 작성 가이드라인
- [x] 라벨, 담당자, 리뷰어 지정

## PR 타입
어떤 유형의 PR인지 체크해주세요.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## PR 설명
Project 생성기능추가 

## 작업사항
- Project 생성기능 추가
- Valid 추가
 - 제목 30자 제한
 - 요약 150자 제한
- ValidException 추가

2022-12-26 00:58 UTC, tjvm0877 requested changes
`Project` 엔티티에서 `ImageList`지워주세요

2022-12-26 00:58 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/project/controller/ProjectController.java
> +        return new ResponseEntity<>(responseDto, HttpStatus.OK);
`return new ResponseEntity<>(responseDto, HttpStatus.OK);`에서 `<>`를 지워도 되지 않을까여?

2022-12-26 02:31 UTC, tjvm0877 requested changes
리뷰 확인 부탁드립니다.

2022-12-26 02:31 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/project/entity/Project.java
> +import java.util.List;
사용하지 않는 import는 지워주셔도 될 것 같습니다.

2022-12-26 03:20 UTC, seonghyun-1 commented on src/main/java/com/team1/TBBCloneCoding/project/controller/ProjectController.java
> +        return new ResponseEntity<>(responseDto, HttpStatus.OK);
수정하겠습니다!

2022-12-26 03:25 UTC, seonghyun-1 commented on src/main/java/com/team1/TBBCloneCoding/project/entity/Project.java
> +import java.util.List;
확인했습니다!

2022-12-26 05:40 UTC, tjvm0877 requested changes

2022-12-26 05:40 UTC, tjvm0877 commented on src/main/java/com/team1/TBBCloneCoding/project/service/ProjectService.java
> +            // 저장된 이미지를 레포지토리 가져와서 연결 -> 저장로직은 구현이 안됨
`-> 저장로직은 구현이 안됨` 은 지워주셔도 될 듯 합니다.

2022-12-27 04:36 UTC, tjvm0877 approved these changes

2022-12-27 15:34 UTC, JeongO41 approved these changes
확인했습니다!

2022-12-27 15:34 UTC, JeongO41 commented on src/main/java/com/team1/TBBCloneCoding/project/controller/ProjectController.java
> +@RequestMapping("/api/project")
"/api/tumblebug" 으로 수정해야 할 듯합니다!

2022-12-27 15:41 UTC, merged